default_stages: [commit, push]
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/thlorenz/doctoc.git
    rev: v2.0.0
    hooks:
      - id: doctoc
        name: Add TOC for md files
        files: ^README\.md$|^CONTRIBUTING\.md$
        args:
          - "--maxlevel"
          - "3"
  - repo: local
    hooks:
      - id: pylint_application
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: src
        args:
          [
            "--max-line-length=120",
            "--disable=protected-access,no-self-use,too-few-public-methods,no-name-in-module",
            "-rn"
          ]
