{{- if ((.Values.imageCredentials).password) -}}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-access
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
