apiVersion: v1
kind: Service
metadata:
  name: {{ include "fast-api-webapp.fullname" . }}
  labels:
    {{- include "fast-api-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.svc.port }}
      targetPort: {{ .Values.metrics.svc.port }}
      protocol: TCP
      name: {{ .Values.metrics.svc.name }}
    {{- end }}
  selector:
    {{- include "fast-api-webapp.selectorLabels" . | nindent 4 }}
